services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: btbs420-dev-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - btbs420-sql-data:/var/opt/mssql

volumes:
  btbs420-sql-data:
